services:
  app:
    environment:
      PYTHONUNBUFFERED: 1
    build: .
    container_name: auto-test-app
    command: gunicorn serving.src.flask_app:app --bind 0.0.0.0:5010 --reload
    ports:
      - 50001:5010
    volumes:
      - .:/app